<%@ Page Language="C#" AutoEventWireup="true" CodeFile="xtjj.aspx.cs" Inherits="xtjj" %>

<%@ Register Src="qttop.ascx" TagName="qttop" TagPrefix="uc5" %>
<%@ Register Src="left3.ascx" TagName="left3" TagPrefix="uc4" %>
<%@ Register Src="left2.ascx" TagName="left2" TagPrefix="uc3" %>
<%@ Register Src="userlog.ascx" TagName="userlog" TagPrefix="uc2" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Secand_hand_car_trading_platform-Systemintroduction</title>
    <link href="qtimages/CSS.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
.STYLE1 {color: #FFFFFF}
.STYLE2 {font-size: 25pt}
    .auto-style1 {
        font-family: "Times New Roman";
        letter-spacing: 0.0000pt;
        text-transform: none;
        font-style: italic;
        font-size: 10.5000pt;
        background: rgb(255,255,255);
    }
-->
</style>
</head>
<body  bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
    <form id="form1" runat="server">
    <div style="text-align: center">
    <table id="__01" width="1001" height="1240" border="0" cellpadding="0" cellspacing="0">
<tr>
		<td height="93" colspan="2" background="qtimages/hsglanse_01.gif"><table width="100%" height="90" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td width="31%" height="18">&nbsp;</td>
            <td width="69%">&nbsp;</td>
          </tr>
          <tr>
            <td height="31"><div style="font-family:宋体; color:#FFFFFF; filter:Glow(Color=#000000,Strength=2); WIDTH: 217%; FONT-WEIGHT: bold; FONT-SIZE: 19pt; margin-top:5pt">&nbsp;&nbsp;&nbsp;<span class="STYLE2">Secand hand car trading platform</span></div></td>
            <td valign="top">&nbsp;</td>
          </tr>
        </table></td>
	</tr>
	<tr>
		<td height="40" colspan="2" background="qtimages/hsglanse_02.gif">
          <uc5:qttop ID="Qttop1" runat="server" />
        </td>
	</tr>
	<tr>
		<td colspan="2"><table id="Table1" width="1001" height="267" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td rowspan="3"><img src="qtimages/hsglanse_03_01.gif" width="29" height="267" alt=""></td>
            <td><img src="qtimages/hsglanse_03_02.gif" width="944" height="10" alt=""></td>
            <td rowspan="3"><img src="qtimages/hsglanse_03_03.gif" width="28" height="267" alt=""></td>
          </tr>
          <tr>
            <td><table id="Table2" width="944" height="28" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td><img src="qtimages/hsglanse_03_04_01.gif" width="9" height="28" alt=""></td>
                <td width="675" background="qtimages/hsglanse_03_04_02.gif"><marquee behavior="scroll" onMouseOver="this.stop()" onMouseOut="this.start()" scrollamount="2" scrolldelay="6" direction="left" width="650" >Welome.wish you have a good experince!</marquee></td>
                <td width="246" background="qtimages/hsglanse_03_04_02.gif"><table width="100%" border="0" cellpadding="0" cellspacing="0">
                  <tr>
                    <td width="17%" class="lancu">Search:                      </td>
                    <td width="62%"><input type="text" name="textfield"></td>
                    <td width="21%"><input type="image" name="imageField" src="qtimages/1.gif"></td>
                  </tr>
                </table></td>
                <td><img src="qtimages/hsglanse_03_04_04.gif" width="14" height="28" alt=""></td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td height="229" background="qtimages/hsglanse_03_05.gif">&nbsp;</td>
          </tr>
        </table></td>
	</tr>
	<tr>
		<td  valign="top"><table id="Table3" width="300" height="712" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td rowspan="3"><img src="qtimages/hsglanse_04_01.gif" width="19" height="712" alt=""></td>
            <td style="width: 285px">
                <uc2:userlog ID="Userlog1" runat="server" />
            </td>
          </tr>
          <tr>
            <td style="width: 285px"> 
                <uc3:left2 ID="Left2_1" runat="server" />
                <uc4:left3 ID="Left3_1" runat="server" />
            </td>
          </tr>
          
          <tr>
            <td style="width: 285px"><img src="qtimages/hsglanse_04_05.gif" width="281" height="27" alt=""></td>
          </tr>
        </table></td>
		<td style="width: 703px" valign="top"><table id="Table7" width="701" height="712" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td colspan="3"><img src="qtimages/hsglanse_05_01.gif" width="701" height="7" alt=""></td>
          </tr>
          <tr>
            <td width="8" height="705" rowspan="2" background="qtimages/hsglanse_05_02.gif">&nbsp;</td>
            <td valign="top"><table id="Table8" width="652" height="214" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td colspan="2" style="height: 1px" valign="top"><img src="qtimages/hsglanse_05_03_01.gif" width="652" height="11" alt=""><br /><table width="100%" border="0" cellspacing="0" cellpadding="0" style="height: 28px">
  <tr>
    <td background="qtimages/8.gif" style="height: 24px" align="left">&nbsp; &nbsp; Now location：<a href="default.aspx">Home</a><a href="newslist.aspx"></a>&gt;&gt;System Introduction</td>
  </tr>
</table>
                    <table border="0" height="381" width="100%">
                        <tr>
                            <td align="center" height="41">
                                <strong>System Introduction</strong>
                                &nbsp;</td>
                        </tr>
                        <tr>
                            <td height="294" valign="top" align="left">
                                &nbsp; &nbsp; &nbsp;&nbsp;
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">According to EU GDPR, when the system collects user information, we will ensure that the information uploaded by all users will only be used for second-hand car transactions. The personal information and vehicle information of users will only be used as the transaction display content of the website. We ensure that the website will not use the user information for purposes other than the website or for third-party organizations and institutions.<o:p></o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">According to ‘</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">General Data Protection Regulation</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(EU) 
                                    2016/679</span><span style="mso-spacerun: 'yes'; font-family: 'Segoe UI'; mso-fareast-font-family: 宋体; color: rgb(68,68,68); letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">’</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(2016)</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: 'Segoe UI'; mso-hansi-font-family: 'Segoe UI'; mso-bidi-font-family: 'Segoe UI'; color: rgb(68,68,68); letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:Arial;
mso-hansi-font-family:Arial;mso-bidi-font-family:Arial;letter-spacing:0.0000pt;
text-transform:none;font-style:normal;font-size:10.5000pt;
mso-font-kerning:1.0000pt;">point(a) point(b)</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:宋体;
letter-spacing:0.0000pt;font-weight:normal;text-transform:none;
font-style:normal;font-size:10.5000pt;mso-font-kerning:1.0000pt;">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">of </span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">Article13</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(1)</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">, 
                                    we will provide the contact information of data administrator to the user, and the user can contact the data manager to provide technical support for the data in a timely manner.<o:p></o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">On the other hand, According to ‘</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">General Data Protection Regulation</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(EU) 
                                    2016/679</span><span style="mso-spacerun: 'yes'; font-family: 'Segoe UI'; mso-fareast-font-family: 宋体; color: rgb(68,68,68); letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">’</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(2016)</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: 'Segoe UI'; mso-hansi-font-family: 'Segoe UI'; mso-bidi-font-family: 'Segoe UI'; color: rgb(68,68,68); letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:Arial;
mso-hansi-font-family:Arial;mso-bidi-font-family:Arial;letter-spacing:0.0000pt;
text-transform:none;font-style:normal;font-size:10.5000pt;
mso-font-kerning:1.0000pt;">point(a)</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">of </span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">Article13</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(2).
                                    </span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">we will store user data for up to one year, during which time the data will be protected as mentioned above. After one year, we will take the initiative to clean up the user data and inform the user that if the user wants to continue to publish information </span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">on </span>
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">the website or use the functions of the website, they can apply for an update and upload the information again.<o:p></o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">At the same time, based on point (a) of Article 6 (1) or point (a) of Article 9 (2), users have the right to withdraw at any time. They can withdraw their data in time by contacting data management personnel, without affecting the legality of consent based processing before withdrawal.<o:p></o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">A</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">ccording to </span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">‘</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">General 
                                    Data Protection Regulation</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(EU) 2016/679</span><span style="mso-spacerun: 'yes'; font-family: 'Segoe UI'; mso-fareast-font-family: 宋体; color: rgb(68,68,68); letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">’</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(2016)</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">Article
                                    </span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">1</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">6 , users also have the right to correct their own information in time. Users can get in touch with the data administrator to change incorrect information, or modify part of the data through the personal center.</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><o:p></o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">Although minors cannot afford the legal effect, they have the right to buy used cars, all systems will be in accordance with the </span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">‘</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">General 
                                    Data Protection Regulation</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(EU) 2016/679</span><span style="mso-spacerun: 'yes'; font-family: 'Segoe UI'; mso-fareast-font-family: 宋体; color: rgb(68,68,68); letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">’</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(2016)</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">Article
                                    </span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">8</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">. If the child is over 16 years old, data collection is legal. If the child is under 16 years old, it must be carried out with the consent of parents or effective guardians. Therefore, we hereby remind all guardians that if the user is under 16 years old, please accompany and consent the minor user to use the system.</span><span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="宋体">（</font>The 
                                    legal age in individual countries is no less than 13<font face="宋体">）</font></span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><o:p></o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">U</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">sers should read this statement before registering and uploading any information to ensure that users understand the usage method and rights of our system for their data.<o:p></o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: 宋体; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">References list</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><o:p></o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">‘</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">General Data Protection Regulation</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(EU) 
                                    2016/679</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">on the protection of natural persons with regard to the processing of personal data and on the free movement of such data</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">’ </span><i>
                                    <span class="auto-style1" style="mso-spacerun: 'yes'; mso-fareast-font-family: 宋体; mso-shading: rgb(255,255,255);">Official Journal</span><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">&nbsp;</span></i><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">L119, p. 41,</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:宋体;
letter-spacing:0.0000pt;font-weight:normal;text-transform:none;
font-style:normal;font-size:10.5000pt;mso-font-kerning:1.0000pt;">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">Article13(1), </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:宋体;
letter-spacing:0.0000pt;text-transform:none;font-style:normal;
font-size:10.5000pt;mso-font-kerning:1.0000pt;">point(a) </span><i><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);"><o:p></o:p></span></i>
                                </p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">‘</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">General Data Protection Regulation</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(EU) 
                                    2016/679</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">on the protection of natural persons with regard to the processing of personal data and on the free movement of such data</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">’ </span><i>
                                    <span class="auto-style1" style="mso-spacerun: 'yes'; mso-fareast-font-family: 宋体; mso-shading: rgb(255,255,255);">Official Journal</span><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">&nbsp;</span></i><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">L119, p. 36, </span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">Article 6 (1), point (a)</span><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);"><o:p></o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">‘</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">General Data Protection Regulation</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(EU) 
                                    2016/679</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">on the protection of natural persons with regard to the processing of personal data and on the free movement of such data</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">’ </span><i>
                                    <span class="auto-style1" style="mso-spacerun: 'yes'; mso-fareast-font-family: 宋体; mso-shading: rgb(255,255,255);">Official Journal</span><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">&nbsp;</span></i><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">L119, p. 38,</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;Article 9 (2), point (a)</span><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);"><o:p></o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">‘</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">General Data Protection Regulation</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(EU) 
                                    2016/679</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">on the protection of natural persons with regard to the processing of personal data and on the free movement of such data</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">’ </span><i>
                                    <span class="auto-style1" style="mso-spacerun: 'yes'; mso-fareast-font-family: 宋体; mso-shading: rgb(255,255,255);">Official Journal</span><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">&nbsp;</span></i><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">L119, p. 43, </span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">Article 16</span><i><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);"><o:p></o:p></span></i></p>
                                <p class="MsoNormal">
                                    <span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);"><o:p>&nbsp;</o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">‘</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">General Data Protection Regulation</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(EU) 
                                    2016/679</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">on the protection of natural persons with regard to the processing of personal data and on the free movement of such data</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">’ </span><i>
                                    <span class="auto-style1" style="mso-spacerun: 'yes'; mso-fareast-font-family: 宋体; mso-shading: rgb(255,255,255);">Official Journal</span><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">&nbsp;</span></i><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">L119, p. 41,</span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:宋体;
letter-spacing:0.0000pt;font-weight:normal;text-transform:none;
font-style:normal;font-size:10.5000pt;mso-font-kerning:1.0000pt;">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">Article13(1), </span><span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:宋体;
letter-spacing:0.0000pt;text-transform:none;font-style:normal;
font-size:10.5000pt;mso-font-kerning:1.0000pt;">point(b) <o:p></o:p></span>
                                </p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:宋体;
letter-spacing:0.0000pt;text-transform:none;font-style:normal;
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">‘</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">General Data Protection Regulation</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">(EU) 
                                    2016/679</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 'Segoe UI'; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">on the protection of natural persons with regard to the processing of personal data and on the free movement of such data</span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">’ </span><i>
                                    <span class="auto-style1" style="mso-spacerun: 'yes'; mso-fareast-font-family: 宋体; mso-shading: rgb(255,255,255);">Official Journal</span><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">&nbsp;</span></i><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);">L119, p. 37<font face="宋体">，</font></span><span style="mso-spacerun: 'yes'; font-family: Arial; mso-fareast-font-family: 宋体; letter-spacing: 0.0000pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">Article 8</span><i><span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);"><o:p></o:p></span></i></p>
                                <p class="MsoNormal">
                                    <span style="mso-spacerun:'yes';font-family:Arial;mso-fareast-font-family:宋体;
letter-spacing:0.0000pt;text-transform:none;font-style:normal;
font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p>
                                <p class="MsoNormal">
                                    <span class="auto-style1" style="mso-spacerun: 'yes'; mso-shading: rgb(255,255,255);"><o:p>&nbsp;</o:p></span></p>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" heigh="38">
                                &nbsp;<asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="javascript:history.back();">Back</asp:HyperLink></td>
                        </tr>
                    </table>
                    </td>
              </tr>
            </table>
                    </td>
            <td width="41" height="705" rowspan="2" background="qtimages/hsglanse_05_04.gif">&nbsp;</td>
          </tr>
          <tr>
            <td><img src="qtimages/hsglanse_05_09.gif" width="652" height="9" alt=""></td>
          </tr>
        </table></td>
	</tr>
	<tr>
		<td height="123" colspan="2" align="center" background="qtimages/hsglanse_06.gif"><p class="STYLE1">&nbsp;</p>
	    <p class="STYLE1">Copyright:xxxx Phone:xxxxxxxx Student ID:10666177  </p>
      <p class="STYLE1">Supervisor:Steven School:xxxxxx  Major:Computing</p></td>
	</tr>
</table>
    </div>
    </form>
</body>
</html>
